version: '2'
services:
  store:
    image: ${REGISTRY_ADDRESS}/${NAMESPACE}:${VERSION}
    container_name: store
    ports:
      - 8080:8080
    depends_on:
    volumes:
    env_file:
      - docker-compose.env
    restart: always