version: '2'
services:
  store:
    image: 648265802301.dkr.ecr.us-west-2.amazonaws.com/ep/ep-store:0.1.0
    container_name: store
    ports:
      - 8080:8080
    env_file:
      - docker-compose.env
    restart: always